# Generated by Django 5.2.7 on 2026-01-20 04:55

import apps.devices.models.firmware
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique hardware identifier (MAC address or UUID)",
                        max_length=64,
                        unique=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="School Name"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about device location or configuration",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Online"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time device sent diagnostics",
                        null=True,
                        verbose_name="Last Seen",
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        db_index=True,
                        default="0.0.0",
                        max_length=20,
                        verbose_name="Firmware Version",
                    ),
                ),
                (
                    "rtc_synced",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the real-time clock is working correctly",
                        verbose_name="RTC Synced",
                    ),
                ),
                (
                    "wifi_rssi",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="WiFi signal strength in dBm",
                        null=True,
                        verbose_name="WiFi RSSI",
                    ),
                ),
                (
                    "free_heap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Available memory in bytes",
                        null=True,
                        verbose_name="Free Heap",
                    ),
                ),
                (
                    "uptime_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Device uptime in seconds",
                        null=True,
                        verbose_name="Uptime",
                    ),
                ),
                (
                    "mqtt_password_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed password for MQTT broker authentication",
                        max_length=255,
                        verbose_name="MQTT Password Hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmwareVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version, e.g. 1.2.3",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Version must be in format X.Y.Z (e.g. 1.2.3)",
                                regex="^\\d+\\.\\d+\\.\\d+$",
                            )
                        ],
                        verbose_name="Version",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Compiled .bin file for ESP8266",
                        upload_to=apps.devices.models.firmware.firmware_upload_path,
                        verbose_name="Firmware File",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Auto-calculated MD5 hash for integrity verification",
                        max_length=64,
                        verbose_name="MD5 Checksum",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Size in bytes", verbose_name="File Size"
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        help_text="What's new in this version",
                        verbose_name="Changelog",
                    ),
                ),
                (
                    "is_stable",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as stable for production rollout",
                        verbose_name="Is Stable",
                    ),
                ),
                (
                    "min_version",
                    models.CharField(
                        blank=True,
                        help_text="Minimum firmware version that can upgrade to this version",
                        max_length=20,
                        verbose_name="Minimum Required Version",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percentage of devices to target (0-100)",
                        verbose_name="Rollout Percentage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmware Version",
                "verbose_name_plural": "Firmware Versions",
                "db_table": "firmware_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTABatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this update batch",
                        max_length=255,
                        verbose_name="Batch Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "devices_per_hour",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum devices to update per hour (rate limiting)",
                        verbose_name="Devices Per Hour",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start the batch (null = immediate)",
                        null=True,
                        verbose_name="Scheduled Start",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "total_devices",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Devices"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Success Count"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failure Count"
                    ),
                ),
            ],
            options={
                "verbose_name": "OTA Batch",
                "verbose_name_plural": "OTA Batches",
                "db_table": "ota_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTABatchDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("notified", "Notified"),
                            ("downloading", "Downloading"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When OTA command was sent via MQTT",
                        null=True,
                        verbose_name="Notified At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "previous_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Previous Version"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Retry Count"
                    ),
                ),
            ],
            options={
                "verbose_name": "OTA Batch Device",
                "verbose_name_plural": "OTA Batch Devices",
                "db_table": "ota_batch_devices",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "times",
                    models.JSONField(
                        default=list,
                        help_text='List of times in 24h format, e.g. ["08:30", "09:15"]',
                        verbose_name="Ring Times",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Tashkent",
                        help_text="Device timezone for schedule interpretation",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When schedule was last pushed to device via MQTT",
                        null=True,
                        verbose_name="Last Synced",
                    ),
                ),
                (
                    "sync_pending",
                    models.BooleanField(
                        default=True,
                        help_text="Whether schedule needs to be pushed to device",
                        verbose_name="Sync Pending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "device_schedules",
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("device", "Device"),
                            ("server", "Server"),
                            ("mqtt", "MQTT"),
                        ],
                        default="device",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured diagnostic data",
                        verbose_name="Metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices.device",
                        verbose_name="Device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Log",
                "verbose_name_plural": "Device Logs",
                "db_table": "device_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="target_firmware",
            field=models.ForeignKey(
                blank=True,
                help_text="Firmware version this device should update to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_devices",
                to="devices.firmwareversion",
                verbose_name="Target Firmware",
            ),
        ),
    ]
