# Generated by Django 5.2.7 on 2026-01-20 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="otabatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ota_batches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="otabatch",
            name="firmware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ota_batches",
                to="devices.firmwareversion",
                verbose_name="Target Firmware",
            ),
        ),
        migrations.AddField(
            model_name="otabatchdevice",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="devices.otabatch",
                verbose_name="Batch",
            ),
        ),
        migrations.AddField(
            model_name="otabatchdevice",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ota_updates",
                to="devices.device",
                verbose_name="Device",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="devices.device",
                verbose_name="Device",
            ),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["device", "-created_at"], name="device_logs_device__15f61f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["level", "-created_at"], name="device_logs_level_6adfcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["device", "level", "-created_at"],
                name="device_logs_device__da12f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_id", "is_online"], name="devices_device__3381df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["school_name"], name="devices_school__85f52e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["firmware_version"], name="devices_firmwar_ccc0fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "is_online"], name="devices_status_2a6f28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otabatchdevice",
            index=models.Index(
                fields=["batch", "status"], name="ota_batch_d_batch_i_41fe30_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="otabatchdevice",
            unique_together={("batch", "device")},
        ),
    ]
