# Generated by Django 5.2.7 on 2026-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="mqtt_password_hash",
        ),
        migrations.AddField(
            model_name="device",
            name="mqtt_password",
            field=models.CharField(
                blank=True,
                help_text="Password for MQTT broker authentication",
                max_length=128,
                verbose_name="MQTT Password",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="mqtt_username",
            field=models.CharField(
                blank=True,
                help_text="Username for MQTT broker authentication",
                max_length=128,
                verbose_name="MQTT Username",
            ),
        ),
    ]
