# Generated by Django 5.2.7 on 2026-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_remove_device_mqtt_password_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicelog",
            name="device",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_device__3381df_idx",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_status_2a6f28_idx",
        ),
        migrations.RemoveField(
            model_name="device",
            name="free_heap",
        ),
        migrations.RemoveField(
            model_name="device",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="device",
            name="last_seen",
        ),
        migrations.RemoveField(
            model_name="device",
            name="uptime_seconds",
        ),
        migrations.RemoveField(
            model_name="device",
            name="wifi_rssi",
        ),
        migrations.AddField(
            model_name="device",
            name="api_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique API key for device authentication. Auto-generated on creation.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="registered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the device was registered/claimed",
                null=True,
                verbose_name="Registered At",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("unregistered", "Unregistered"),
                    ("pending", "Pending"),
                    ("registered", "Registered"),
                ],
                db_index=True,
                default="unregistered",
                help_text="Whether device has been claimed by a customer",
                max_length=20,
                verbose_name="Registration Status",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="school_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Filled by admin when approving device",
                max_length=255,
                verbose_name="School Name",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_status_9f14cf_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["registration_status"], name="devices_registr_1f098e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["api_key"], name="devices_api_key_b48fbc_idx"),
        ),
        migrations.DeleteModel(
            name="DeviceLog",
        ),
    ]
