# Generated by Django 5.2.7 on 2026-05-21 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("device", "Device"),
                            ("server", "Server"),
                            ("ota", "OTA"),
                            ("mqtt", "MQTT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Device Log",
                "verbose_name_plural": "Device Logs",
                "db_table": "device_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_device__c4b5e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_api_key_b48fbc_idx",
        ),
        migrations.AddField(
            model_name="devicelog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="devices.device",
            ),
        ),
    ]
