# Generated by Django 5.2.7 on 2026-05-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devicelog_remove_device_devices_device__c4b5e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, help_text='Unique API key for device authentication. Auto-generated on creation.', max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Unique hardware identifier (MAC address or UUID)', max_length=64, unique=True, verbose_name='Device ID'),
        ),
    ]
