# Generated by Django 5.2.7 on 2026-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_api_key_alter_device_device_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='devices_school__85f52e_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_firmwar_ccc0fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_status_9f14cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_registr_1f098e_idx',
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_password',
            field=models.CharField(blank=True, help_text='Password for MQTT broker authentication', max_length=256, verbose_name='MQTT Password'),
        ),
    ]
