# Generated by Django 5.2.7 on 2026-05-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_device_last_seen"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["device", "-created_at"], name="devicelog_device_created"
            ),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["level", "-created_at"], name="devicelog_level_created"
            ),
        ),
    ]
