# Generated by Django 5.2.7 on 2026-05-22 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_devicelog_devicelog_device_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "Debug"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("critical", "Critical"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="firmwareversion",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="Auto-calculated SHA-256 hash for integrity verification",
                max_length=64,
                verbose_name="SHA-256 Checksum",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["registration_status", "-created_at"],
                name="idx_device_regstatus_created",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["owner", "-created_at"], name="idx_device_owner_created"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "registration_status"],
                name="idx_device_status_regstatus",
            ),
        ),
    ]
