# Generated by Django 5.2.7 on 2026-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0011_add_debug_log_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Auto-incremented on each schedule change. ESP32 compares to detect updates.",
                verbose_name="Version",
            ),
        ),
    ]
