# Generated by Django 5.2.7 on 2026-05-23 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0012_add_schedule_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("date", models.DateField(verbose_name="date")),
                ("recurring", models.BooleanField(default=False, verbose_name="recurring yearly")),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "db_table": "holidays",
                "ordering": ["date"],
                "unique_together": {("date", "name")},
            },
        ),
    ]
