# Generated by Django 5.2.7 on 2026-06-09 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0025_commandlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="hw_version",
            field=models.CharField(
                db_index=True,
                default="1.0",
                help_text="PCB/sensor revision. Firmware must be compatible with this.",
                max_length=10,
                verbose_name="Hardware Version",
            ),
        ),
        migrations.AddField(
            model_name="firmwareversion",
            name="compatible_hw_versions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='HW revisions this firmware supports, e.g. ["1.0", "1.1"]. Empty = all.',
                verbose_name="Compatible HW Versions",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("times", models.JSONField(verbose_name="Ring Times")),
                (
                    "days_mask",
                    models.PositiveSmallIntegerField(verbose_name="Days Mask"),
                ),
                (
                    "bell_duration",
                    models.PositiveIntegerField(verbose_name="Bell Duration (ms)"),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
            ],
            options={
                "verbose_name": "Schedule History",
                "verbose_name_plural": "Schedule History",
                "db_table": "schedule_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="belllog",
            new_name="bell_logs_device__4d33ef_idx",
            old_name="bell_logs_device__b2e3a4_idx",
        ),
        migrations.RenameIndex(
            model_name="commandlog",
            new_name="devices_com_status_610198_idx",
            old_name="devices_com_status_sent_idx",
        ),
        migrations.AlterField(
            model_name="devicealert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("panic", "Panic"),
                    ("lockdown", "Lockdown"),
                    ("emergency_ring", "Emergency Ring"),
                    ("offline", "Device Offline"),
                    ("rtc_drift", "RTC Drift"),
                    ("rtc_battery_dead", "RTC Battery Dead"),
                    ("schedule_stale", "Schedule Stale"),
                ],
                max_length=20,
                verbose_name="alert type",
            ),
        ),
        migrations.AddField(
            model_name="schedulehistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Changed By",
            ),
        ),
        migrations.AddField(
            model_name="schedulehistory",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_history",
                to="devices.device",
                verbose_name="Device",
            ),
        ),
    ]
