# Generated by Django 5.2.7 on 2026-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user's email has been verified",
                verbose_name="Email Verified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="School or organization name",
                max_length=255,
                verbose_name="Organization Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=100,
                null=True,
                verbose_name="Verification Token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="When the verification token expires",
                null=True,
                verbose_name="Token Expires",
            ),
        ),
    ]
