# Generated by Django 5.2.7 on 2026-02-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified_user_organization_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")],
                db_index=True,
                default="USER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
