# Generated by Django 5.2.7 on 2026-05-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Username"
            ),
        ),
    ]
