# Generated by Django 5.2.7 on 2026-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('USER', 'User')], default='USER', max_length=20, verbose_name='Role'),
        ),
    ]
